on:
  push:   
    branches:
      - master





jobs:    
  build:
    runs-on: ubuntu-latest

    steps:
        - name: 'Testing Github actions'
          run: pwd
  
        - name: 'Testing printing'
          run: echo abdoo

        - uses: Actions/checkout@v3

        - name: 'print files'
          run: ls

        - name: 'Login to Docker'
          run: docker login --username abdo1111 --password ${{secrets.DOCKER_TOKEN}}
  
        - name: 'Building Docker Image'
          run: docker build -t abdo1111/myimage .
  
        - name: 'Push Docker Image'
          run: docker push $abdo1111/myimage:latest