on:
  push:   
    branches:
      - master





jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v3

      - name: 'Login to Docker Hub'
        run: docker login --username abdo1111 --password dckr_pat_WGMm67z4w482IN--LfaQNtgMsk4

      - name: 'Build Docker Image'
        run: docker build -t abdo1111/myimage:latest .

      - name: 'Push Docker Image'
        run: docker push abdo1111/myimage:latest
