on:
  push:   
    branches:
      - master





jobs:    
  build:
    runs-on: ubuntu-latest

    steps:
        - name: 'Testing Github actions'
          run: pwd
  
        - name: 'Testing printing'
          run: echo abdoo

        - uses: Actions/checkout@v3

        - name: 'print files'
          run: ls

        - name: 'login'
          run: docker login --username ${{secrets.USERNAME}} --password ${{secrets.TOKEN}}

        - name: 'BUildin docker image'
          run: docker build -t ${{secrets.USERNAME}}/myimage .
          
        - name: 'push'
          run: docker push ${{secrets.USERNAME}}/myimage 